-- The API is the only database entry point. RLS protects accidental direct
-- access from Supabase clients; the server-side database role remains the
-- trusted application boundary.
ALTER TABLE IF EXISTS public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."UserRole" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RefreshToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."UserPreference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Recipes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Ingredient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RecipeIngredient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RecipeStep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RecipeTag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Watchlist" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Collection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CollectionRecipe" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."MealPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."MealPlanItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CookingLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CookingPhoto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Rating" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ModerationEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."_prisma_migrations" ENABLE ROW LEVEL SECURITY;
